### ISSUE TITLE
No tooltips on windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [aBothe/Mono-D#609]
Tooltips do not work at all. May be there's a setting or the like to enable them?

**Comment by aBothe** [comment]
In my linux installation, everything works normally. Do you get any errors in the log?
Please check out the latest log via `Help`-menu > `Open Log directory`.

**Comment by vasily-kirichenko** [comment]
Yes, there are some exceptions related to D tooltips:

```
INFO [2015-05-09 18:59:49Z]: TooltipProvider: Getting tool tip
WARNING [2015-05-09 18:59:49Z]: TooltipProvider: ParseAndCheckResults not found
Exception in tooltip provider MonoDevelop.D.Gui.DToolTipProvider GetItem:
System.NullReferenceException: Object reference not set to an instance of an object.
   at D_Parser.Resolver.LooseResolution.LookupIdRawly(ParseCacheView parseCache, ISyntaxRegion o, DModule oContext)
   at D_Parser.Resolver.LooseResolution.<ResolveTypeLoosely>c__AnonStorey0.<>m__0()
   at D_Parser.Completion.CodeCompletion.DoTimeoutableCompletionTask(ICompletionDataGenerator cdgen, ResolutionContext ctxt, Action ac, Int32 timeout)
   at D_Parser.Resolver.LooseResolution.ResolveTypeLoosely(IEditorData editor, ISyntaxRegion o, NodeResolutionAttempt& resolutionAttempt)
   at MonoDevelop.D.Gui.DToolTipProvider.GetItem(TextEditor editor, Int32 offset)
   at Mono.TextEditor.TextArea.TooltipTimer()
INFO [2015-05-09 19:00:45Z]: TooltipProvider: Getting tool tip
WARNING [2015-05-09 19:00:45Z]: TooltipProvider: ParseAndCheckResults not found
-------- Exception while creating tooltip:
System.MissingMethodException: Method not found: 'Void MonoDevelop.Components.PopoverWindow.RepositionWindow(System.Nullable`1<Gdk.Rectangle>)'.
   at MonoDevelop.D.Gui.DToolTipProvider.CreateTooltipWindow(TextEditor editor, Int32 offset, ModifierType modifierState, TooltipItem item)
   at MonoDevelop.D.Gui.DToolTipProvider.ShowTooltipWindow(TextEditor editor, Int32 offset, ModifierType modifierState, Int32 mouseX, Int32 mouseY, TooltipItem item)
   at Mono.TextEditor.TextArea.TooltipTimer()
INFO [2015-05-09 19:00:47Z]: TooltipProvider: Getting tool tip
WARNING [2015-05-09 19:00:47Z]: TooltipProvider: ParseAndCheckResults not found
-------- Exception while creating tooltip:
System.MissingMethodException: Method not found: 'Void MonoDevelop.Components.PopoverWindow.RepositionWindow(System.Nullable`1<Gdk.Rectangle>)'.
   at MonoDevelop.D.Gui.DToolTipProvider.CreateTooltipWindow(TextEditor editor, Int32 offset, ModifierType modifierState, TooltipItem item)
   at MonoDevelop.D.Gui.DToolTipProvider.ShowTooltipWindow(TextEditor editor, Int32 offset, ModifierType modifierState, Int32 mouseX, Int32 mouseY, TooltipItem item)
   at Mono.TextEditor.TextArea.TooltipTimer()
INFO [2015-05-09 19:04:43Z]: TooltipProvider: Getting tool tip
WARNING [2015-05-09 19:04:43Z]: TooltipProvider: ParseAndCheckResults not found
-------- Exception while creating tooltip:
System.MissingMethodException: Method not found: 'Void MonoDevelop.Components.PopoverWindow.RepositionWindow(System.Nullable`1<Gdk.Rectangle>)'.
   at MonoDevelop.D.Gui.DToolTipProvider.CreateTooltipWindow(TextEditor editor, Int32 offset, ModifierType modifierState, TooltipItem item)
   at MonoDevelop.D.Gui.DToolTipProvider.ShowTooltipWindow(TextEditor editor, Int32 offset, ModifierType modifierState, Int32 mouseX, Int32 mouseY, TooltipItem item)
   at Mono.TextEditor.TextArea.TooltipTimer()
```

**Comment by aBothe** [comment]
Weird. Which XamarinStudio version do you've got?

**Comment by vasily-kirichenko** [comment]
```
=== Xamarin Studio ===

Version 5.8.3 (build 1)
Installation UUID: 38dc9554-04e1-4184-a473-93937eaea244
Runtime:
	Microsoft .NET 4.0.30319.18444
	GTK+ 2.24.22 (MS-Windows theme)
	GTK# 2.12.26

=== Xamarin.Android ===

Not Installed

=== Xamarin Android Player ===

Not Installed

=== Build Information ===

Release ID: 508030001
Git revision: 6e8e725e0d689351901c2c70453bfa4ea25e293b
Build date: 2015-04-06 15:20:49-04
Xamarin addins: 051cd5f8c1b5dbfc87eaef80a74aec03f34c60a8

=== Operating System ===

Windows 6.1.7601.65536 (64-bit)
```

![image](https://cloud.githubusercontent.com/assets/873919/7551703/1277026e-f69c-11e4-984b-1cb37e7e4159.png)

**Comment by aBothe** [comment]
I think version 5.8.3 seems outdated. There already is a 5.9 version available - http://www.monodevelop.com/download/

**Comment by aBothe** [comment]
This issue should be related to #605

**Comment by vasily-kirichenko** [comment]
Yes, you are right. I updated xamarin to version 5.9 and everything works ok now :)
